### ISSUE TITLE
Duplicate data in auth/session

### ISSUE THREAD

**Issue by christohill** [pstaender/silverstripe-restful-api#10]
I'm just wondering if I maybe I'm doing something wrong, but I'm getting duplicated data in auth/session.

**Example config**
```yaml
ApiController:
  underscoreFields: true
  useAccesstokenAuth: true
  accessTokenPropertyName: 'X-Accesstoken'
  useDataProperty: false
  useAccesstokenExclusivelyAsAuthentication: false 
AuthSession:
  validInMinutesFromNow: 1008000
  adminAccessToken: '84c44b7ee63a9919aa272673eecfc7f9b7424e47'
  requiredGroup: null
  requiredPermission: null
  urlSegment: 'auth'
ApiSchemaController:
  allowedModels:
    - Member
DataObject:
  jsonDateFormat: 'D '
  castDataObjectFields: false
  resolveHasOneRelations: false
  resolveHasManyRelations: false
  extensions:
    - ApiDataObject
```

**Example response (auth/session)**
```json
{
  "session": {
    "member": {
      "id": 1,
      "first_name": "Default Admin",
      "surname": null,
      "email": "admin"
    },
    "accesstoken": "1d06aa98e8a65a636f2de6e7e3e9e47be44614a8",
    "valid_until": "Tue Nov 22 2016 07:28:34 +0100",
    "is_valid": true,
    "valid_until_timestamp": 1479796114,
    "user": {
      "id": 1,
      "first_name": "Default Admin",
      "surname": null,
      "email": "admin"
    },
    "uri": "http://localhost/test/auth/session/"
  },
  "code": 201,
  "message": "resource created succesfully"
}
```
 Also, in some cases "user" is returning has_one relations even with the config setting as **false**

Is there something I'm missing that's causing the user/member duplicate? When I duplicate the module folder from a previous project (around Dec 2015) I don't get the same issue.
